package com.mps.user.service;
import com.mps.audit.service.AuditService; import com.mps.auth.model.*; import com.mps.auth.repository.*; import com.mps.auth.security.UserPrincipal;
import com.mps.organization.model.*; import com.mps.organization.repository.*; import com.mps.user.dto.UserDtos.*;
import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
import java.security.SecureRandom; import java.util.*;
@Service public class UserAdminService {
 private final AppUserRepository users; private final OrganizationRepository organizations; private final DepartmentRepository departments; private final MemberGroupRepository groups; private final RoleRepository roles; private final RefreshTokenRepository refreshTokens; private final PasswordEncoder encoder; private final AuditService audit;
 public UserAdminService(AppUserRepository users,OrganizationRepository organizations,DepartmentRepository departments,MemberGroupRepository groups,RoleRepository roles,RefreshTokenRepository refreshTokens,PasswordEncoder encoder,AuditService audit){this.users=users;this.organizations=organizations;this.departments=departments;this.groups=groups;this.roles=roles;this.refreshTokens=refreshTokens;this.encoder=encoder;this.audit=audit;}
 @Transactional(readOnly=true) public List<UserView> list(UserPrincipal p,String search){return users.findAllByOrganizationIdOrderByLastNameAscFirstNameAsc(p.organizationId()).stream().filter(u->search==null||search.isBlank()||(u.getEmail()+" "+u.getFirstName()+" "+u.getLastName()).toLowerCase().contains(search.toLowerCase())).map(this::view).toList();}
 @Transactional public UserView create(UserPrincipal p,CreateUserRequest r){Organization o=org(p); if(users.existsByOrganizationIdAndEmailIgnoreCase(o.getId(),r.email()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Email already exists."); AppUser u=new AppUser(o,r.email(),encoder.encode(randomPassword()),r.firstName(),r.lastName());u.setAssociations(department(p,r.departmentId()),group(p,r.groupId()));assignRoles(p,u,r.roles());users.save(u);audit.record(o,p.userId(),"USER_CREATED","User",u.getId(),"SUCCESS",Map.of("email",u.getEmail()));return view(u);}
 @Transactional public UserView update(UserPrincipal p,UUID id,UpdateUserRequest r){AppUser u=user(p,id);u.updateProfile(r.firstName(),r.lastName());u.setAssociations(department(p,r.departmentId()),group(p,r.groupId()));audit.record(u.getOrganization(),p.userId(),"USER_UPDATED","User",id,"SUCCESS",Map.of("email",u.getEmail()));return view(u);}
 @Transactional public UserView assign(UserPrincipal p,UUID id,RoleAssignmentRequest r){AppUser u=user(p,id);assignRoles(p,u,r.roles());audit.record(u.getOrganization(),p.userId(),"USER_ROLES_UPDATED","User",id,"SUCCESS",Map.of("roles",u.getRoles().stream().map(Role::getCode).toList()));return view(u);}
 @Transactional public void archive(UserPrincipal p,UUID id){if(id.equals(p.userId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"You cannot archive your own account.");AppUser u=user(p,id);u.archive();refreshTokens.revokeAllActiveForUser(id,java.time.Instant.now());audit.record(u.getOrganization(),p.userId(),"USER_ARCHIVED","User",id,"SUCCESS",Map.of("email",u.getEmail()));}
 @Transactional public UserView restore(UserPrincipal p,UUID id){AppUser u=user(p,id);u.restore();audit.record(u.getOrganization(),p.userId(),"USER_RESTORED","User",id,"SUCCESS",Map.of("email",u.getEmail()));return view(u);}
 private void assignRoles(UserPrincipal p,AppUser u,Set<String> codes){Set<String> requested=codes==null||codes.isEmpty()?Set.of("MEMBER"):codes; if(requested.contains("SUPER_ADMIN")&&!p.authorities().stream().anyMatch(a->a.getAuthority().equals("ROLE_SUPER_ADMIN")))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Cannot assign Super Administrator."); List<Role> found=roles.findAllByCodeIn(requested);if(found.size()!=requested.size())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"One or more roles are invalid.");u.replaceRoles(new HashSet<>(found));}
 private AppUser user(UserPrincipal p,UUID id){return users.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"User not found."));}
 private Organization org(UserPrincipal p){return organizations.findById(p.organizationId()).orElseThrow();}
 private Department department(UserPrincipal p,UUID id){return id==null?null:departments.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid department."));}
 private MemberGroup group(UserPrincipal p,UUID id){return id==null?null:groups.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid group."));}
 private UserView view(AppUser u){return new UserView(u.getId(),u.getEmail(),u.getFirstName(),u.getLastName(),u.getStatus(),u.getDepartment()==null?null:u.getDepartment().getId(),u.getGroup()==null?null:u.getGroup().getId(),u.getRoles().stream().map(Role::getCode).collect(java.util.stream.Collectors.toCollection(TreeSet::new)));}
 private String randomPassword(){byte[] b=new byte[24];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
}
