package com.mps.document;
import com.mps.auth.security.UserPrincipal; import com.mps.common.ApiResponse; import com.mps.document.dto.DocumentDtos.*; import com.mps.document.model.DocumentAudienceType; import com.mps.document.service.DocumentService; import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.util.*;
@RestController @RequestMapping("/api/v1/documents") public class DocumentController { private final DocumentService service; public DocumentController(DocumentService s){service=s;}
 @GetMapping @PreAuthorize("hasAuthority('documents.read')") public ApiResponse<List<DocumentView>> list(@AuthenticationPrincipal UserPrincipal p){return ApiResponse.ok("Documents loaded.",service.list(p));}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('documents.read')") public ApiResponse<DocumentDetail> detail(@AuthenticationPrincipal UserPrincipal p,@PathVariable UUID id){return ApiResponse.ok("Document loaded.",service.detail(p,id));}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasAuthority('documents.manage')") public ApiResponse<DocumentDetail> upload(@AuthenticationPrincipal UserPrincipal p,@RequestParam String title,@RequestParam(required=false) String category,@RequestParam(defaultValue="ORGANIZATION") DocumentAudienceType audienceType,@RequestParam(required=false) UUID audienceReferenceId,@RequestParam(required=false) String versionNotes,@RequestPart("file") MultipartFile file){return ApiResponse.ok("Document uploaded.",service.upload(p,title,category,audienceType,audienceReferenceId,versionNotes,file));}
 @PostMapping(value="/{id}/versions",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasAuthority('documents.manage')") public ApiResponse<DocumentDetail> replace(@AuthenticationPrincipal UserPrincipal p,@PathVariable UUID id,@RequestParam(required=false) String versionNotes,@RequestPart("file") MultipartFile file){return ApiResponse.ok("Document version added.",service.replace(p,id,versionNotes,file));}
 @GetMapping("/{id}/download") @PreAuthorize("hasAuthority('documents.read')") public ResponseEntity<Resource> download(@AuthenticationPrincipal UserPrincipal p,@PathVariable UUID id,@RequestParam(required=false) Integer version){DocumentService.Download d=service.download(p,id,version);return ResponseEntity.ok().contentType(MediaType.parseMediaType(d.contentType())).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(d.filename()).build().toString()).body(d.resource());}
 @PostMapping("/{id}/archive") @PreAuthorize("hasAuthority('documents.manage')") public ApiResponse<Void> archive(@AuthenticationPrincipal UserPrincipal p,@PathVariable UUID id){service.archive(p,id);return ApiResponse.ok("Document archived.",null);}
}
