package com.mps.announcement.service;
import com.mps.announcement.dto.AnnouncementDtos.*; import com.mps.announcement.model.*; import com.mps.announcement.repository.AnnouncementRepository; import com.mps.audit.service.AuditService; import com.mps.auth.model.AppUser; import com.mps.auth.repository.AppUserRepository; import com.mps.auth.security.UserPrincipal; import com.mps.notification.service.NotificationService; import com.mps.organization.model.Organization; import com.mps.organization.repository.OrganizationRepository; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.time.Instant; import java.util.*;
@Service public class AnnouncementService{
 private final AnnouncementRepository announcements; private final OrganizationRepository organizations; private final AppUserRepository users; private final NotificationService notifications; private final AuditService audit;
 public AnnouncementService(AnnouncementRepository a,OrganizationRepository o,AppUserRepository u,NotificationService n,AuditService audit){announcements=a;organizations=o;users=u;notifications=n;this.audit=audit;}
 @Transactional(readOnly=true) public List<AnnouncementView> list(UserPrincipal p){return announcements.findAllByOrganizationIdOrderByCreatedAtDesc(p.organizationId()).stream().filter(a->visible(a,p)).map(this::view).toList();}
 @Transactional public AnnouncementView create(UserPrincipal p,CreateAnnouncementRequest r){if(r.expiresAt()!=null&&r.publishAt()!=null&&!r.expiresAt().isAfter(r.publishAt()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Expiration must be after publication.");Organization org=organizations.findById(p.organizationId()).orElseThrow();Announcement a=announcements.save(new Announcement(org,r.title(),r.content(),r.audienceType(),r.audienceReferenceId(),r.publishAt(),r.expiresAt(),p.userId()));audit.record(org,p.userId(),"ANNOUNCEMENT_CREATED","Announcement",a.getId(),"SUCCESS",Map.of("audience",r.audienceType().name()));return view(a);}
 @Transactional public AnnouncementView publish(UserPrincipal p,UUID id){Announcement a=find(p,id);try{a.publish();}catch(IllegalStateException e){throw new ResponseStatusException(HttpStatus.CONFLICT,e.getMessage());}List<AppUser> recipients=resolveRecipients(a);notifications.notifyUsers(a.getOrganization(),recipients,"ANNOUNCEMENT_PUBLISHED",a.getTitle(),a.getContent(),"Announcement",a.getId(),true);audit.record(a.getOrganization(),p.userId(),"ANNOUNCEMENT_PUBLISHED","Announcement",id,"SUCCESS",Map.of("recipients",recipients.size()));return view(a);}
 @Transactional public AnnouncementView archive(UserPrincipal p,UUID id){Announcement a=find(p,id);a.archive();audit.record(a.getOrganization(),p.userId(),"ANNOUNCEMENT_ARCHIVED","Announcement",id,"SUCCESS",Map.of());return view(a);}
 private Announcement find(UserPrincipal p,UUID id){return announcements.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Announcement not found."));}
 private List<AppUser> resolveRecipients(Announcement a){List<AppUser> all=users.findAllByOrganizationIdOrderByLastNameAscFirstNameAsc(a.getOrganization().getId());return all.stream().filter(u->switch(a.getAudienceType()){case ORGANIZATION->true;case USER->u.getId().equals(a.getAudienceReferenceId());case DEPARTMENT->u.getDepartment()!=null&&u.getDepartment().getId().equals(a.getAudienceReferenceId());case GROUP->u.getGroup()!=null&&u.getGroup().getId().equals(a.getAudienceReferenceId());case ROLE->u.getRoles().stream().anyMatch(r->r.getId().equals(a.getAudienceReferenceId()));}).toList();}
 private boolean visible(Announcement a,UserPrincipal p){boolean manager=p.authorities().stream().anyMatch(x->x.getAuthority().equals("announcements.manage"));if(manager)return a.getStatus()!=AnnouncementStatus.ARCHIVED;if(a.getStatus()!=AnnouncementStatus.PUBLISHED)return false;if(a.getExpiresAt()!=null&&!a.getExpiresAt().isAfter(Instant.now()))return false;return resolveRecipients(a).stream().anyMatch(u->u.getId().equals(p.userId()));}
 private AnnouncementView view(Announcement a){return new AnnouncementView(a.getId(),a.getTitle(),a.getContent(),a.getAudienceType(),a.getAudienceReferenceId(),a.getStatus(),a.getPublishAt(),a.getExpiresAt(),a.getPublishedAt(),a.getCreatedAt());}
}
