package com.mps.organization.service;
import com.mps.audit.service.AuditService; import com.mps.auth.security.UserPrincipal;
import com.mps.organization.dto.OrganizationDtos.*; import com.mps.organization.model.*; import com.mps.organization.repository.*;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
import java.time.ZoneId; import java.util.List; import java.util.Map; import java.util.UUID;
@Service public class OrganizationAdminService {
 private final OrganizationRepository organizations; private final DepartmentRepository departments; private final MemberGroupRepository groups; private final AuditService audit;
 public OrganizationAdminService(OrganizationRepository organizations,DepartmentRepository departments,MemberGroupRepository groups,AuditService audit){this.organizations=organizations;this.departments=departments;this.groups=groups;this.audit=audit;}
 @Transactional(readOnly=true) public OrganizationView get(UserPrincipal p){return view(org(p.organizationId()));}
 @Transactional public OrganizationView update(UserPrincipal p,UpdateOrganizationRequest r){Organization o=org(p.organizationId());try{ZoneId.of(r.timezone());}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid timezone.");}o.update(r.name(),r.timezone()); organizations.save(o); audit.record(o,p.userId(),"ORGANIZATION_UPDATED","Organization",o.getId(),"SUCCESS",Map.of("name",o.getName(),"timezone",o.getTimezone())); return view(o);}
 @Transactional(readOnly=true) public List<UnitView> departments(UserPrincipal p){return departments.findAllByOrganizationIdAndStatusOrderByName(p.organizationId(),"ACTIVE").stream().map(this::view).toList();}
 @Transactional public UnitView createDepartment(UserPrincipal p,UnitRequest r){Organization o=org(p.organizationId()); if(departments.existsByOrganizationIdAndNameIgnoreCaseAndStatusNot(o.getId(),r.name(),"ARCHIVED")) throw new ResponseStatusException(HttpStatus.CONFLICT,"Department name already exists."); Department d=departments.save(new Department(o,r.name(),r.description())); audit.record(o,p.userId(),"DEPARTMENT_CREATED","Department",d.getId(),"SUCCESS",Map.of("name",d.getName())); return view(d);}
 @Transactional public UnitView updateDepartment(UserPrincipal p,UUID id,UnitRequest r){Department d=department(p,id);d.update(r.name(),r.description());audit.record(d.getOrganization(),p.userId(),"DEPARTMENT_UPDATED","Department",id,"SUCCESS",Map.of("name",d.getName()));return view(d);}
 @Transactional public void archiveDepartment(UserPrincipal p,UUID id){Department d=department(p,id);d.archive();audit.record(d.getOrganization(),p.userId(),"DEPARTMENT_ARCHIVED","Department",id,"SUCCESS",Map.of("name",d.getName()));}
 @Transactional(readOnly=true) public List<UnitView> groups(UserPrincipal p){return groups.findAllByOrganizationIdAndStatusOrderByName(p.organizationId(),"ACTIVE").stream().map(this::view).toList();}
 @Transactional public UnitView createGroup(UserPrincipal p,UnitRequest r){Organization o=org(p.organizationId()); if(groups.existsByOrganizationIdAndNameIgnoreCaseAndStatusNot(o.getId(),r.name(),"ARCHIVED")) throw new ResponseStatusException(HttpStatus.CONFLICT,"Group name already exists."); Department d=r.departmentId()==null?null:department(p,r.departmentId()); MemberGroup g=groups.save(new MemberGroup(o,d,r.name(),r.description()));audit.record(o,p.userId(),"GROUP_CREATED","Group",g.getId(),"SUCCESS",Map.of("name",g.getName()));return view(g);}
 @Transactional public UnitView updateGroup(UserPrincipal p,UUID id,UnitRequest r){MemberGroup g=group(p,id); Department d=r.departmentId()==null?null:department(p,r.departmentId());g.update(d,r.name(),r.description());audit.record(g.getOrganization(),p.userId(),"GROUP_UPDATED","Group",id,"SUCCESS",Map.of("name",g.getName()));return view(g);}
 @Transactional public void archiveGroup(UserPrincipal p,UUID id){MemberGroup g=group(p,id);g.archive();audit.record(g.getOrganization(),p.userId(),"GROUP_ARCHIVED","Group",id,"SUCCESS",Map.of("name",g.getName()));}
 private Organization org(UUID id){return organizations.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Organization not found."));}
 private Department department(UserPrincipal p,UUID id){return departments.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Department not found."));}
 private MemberGroup group(UserPrincipal p,UUID id){return groups.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Group not found."));}
 private OrganizationView view(Organization o){return new OrganizationView(o.getId(),o.getName(),o.getTimezone(),o.getStatus());}
 private UnitView view(Department d){return new UnitView(d.getId(),d.getName(),d.getDescription(),d.getStatus(),null);}
 private UnitView view(MemberGroup g){return new UnitView(g.getId(),g.getName(),g.getDescription(),g.getStatus(),g.getDepartment()==null?null:g.getDepartment().getId());}
}
