package com.mps.assignment.model;
import com.mps.auth.model.AppUser; import com.mps.organization.model.Organization; import com.mps.schedule.model.ScheduleEvent; import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="assignment") public class Assignment {
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="organization_id") private Organization organization; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="schedule_id") private ScheduleEvent schedule; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="assignee_id") private AppUser assignee;
 @Column(name="assignment_type",nullable=false,length=120) private String assignmentType; @Column(nullable=false,length=200) private String title; @Column(length=1000) private String notes; @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private AssignmentStatus status=AssignmentStatus.DRAFT; @Column(name="override_reason",length=500) private String overrideReason; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="reassigned_from") private AppUser reassignedFrom; @Column(name="created_by",nullable=false) private UUID createdBy; @Column(name="created_at",nullable=false) private Instant createdAt=Instant.now(); @Column(name="updated_at",nullable=false) private Instant updatedAt=Instant.now(); @Version private long version;
 protected Assignment(){} public Assignment(Organization o,ScheduleEvent s,AppUser a,String type,String title,String notes,UUID by,String override){organization=o;schedule=s;assignee=a;assignmentType=type.trim();this.title=title.trim();this.notes=norm(notes);createdBy=by;overrideReason=norm(override);}
 public void schedule(){if(status!=AssignmentStatus.DRAFT)throw new IllegalStateException("Only draft assignments can be scheduled.");status=AssignmentStatus.SCHEDULED;updatedAt=Instant.now();}
 public void reassign(AppUser replacement,String reason){if(status==AssignmentStatus.COMPLETED||status==AssignmentStatus.CANCELLED||status==AssignmentStatus.ARCHIVED)throw new IllegalStateException("Assignment cannot be reassigned.");reassignedFrom=assignee;assignee=replacement;overrideReason=norm(reason);updatedAt=Instant.now();}
 public UUID getId(){return id;} public ScheduleEvent getSchedule(){return schedule;} public AppUser getAssignee(){return assignee;} public String getAssignmentType(){return assignmentType;} public String getTitle(){return title;} public String getNotes(){return notes;} public AssignmentStatus getStatus(){return status;} public String getOverrideReason(){return overrideReason;} public AppUser getReassignedFrom(){return reassignedFrom;} public long getVersion(){return version;}
 private static String norm(String s){return s==null||s.isBlank()?null:s.trim();}
}
