package com.mps.assignment.service;
import com.mps.assignment.dto.AssignmentDtos.*; import com.mps.assignment.model.*; import com.mps.assignment.repository.AssignmentRepository; import com.mps.audit.service.AuditService; import com.mps.auth.model.AppUser; import com.mps.auth.repository.AppUserRepository; import com.mps.auth.security.UserPrincipal; import com.mps.schedule.model.*; import com.mps.schedule.repository.ScheduleEventRepository; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@Service public class AssignmentService { private final AssignmentRepository repo; private final ScheduleEventRepository schedules; private final AppUserRepository users; private final ConflictDetectionService conflicts; private final AuditService audit;
 public AssignmentService(AssignmentRepository r,ScheduleEventRepository s,AppUserRepository u,ConflictDetectionService c,AuditService a){repo=r;schedules=s;users=u;conflicts=c;audit=a;}
 @Transactional(readOnly=true) public List<AssignmentView> list(UserPrincipal p,UUID scheduleId){schedule(p,scheduleId);return repo.findAllByOrganizationIdAndScheduleIdOrderByAssignmentTypeAsc(p.organizationId(),scheduleId).stream().map(a->view(p,a)).toList();}
 @Transactional public AssignmentView create(UserPrincipal p,CreateAssignmentRequest req){ScheduleEvent s=schedule(p,req.scheduleId());if(s.getStatus()!=ScheduleStatus.DRAFT)throw new ResponseStatusException(HttpStatus.CONFLICT,"Assignments can only be added while the schedule is draft."); AppUser assignee=req.assigneeId()==null?null:user(p,req.assigneeId()); List<ConflictView> found=conflicts.detect(p.organizationId(),s,assignee); if(conflicts.hasBlocking(found))throw new ResponseStatusException(HttpStatus.CONFLICT,found.stream().filter(ConflictView::blocking).map(ConflictView::message).findFirst().orElse("Blocking conflict.")); if(!found.isEmpty()&&(req.overrideReason()==null||req.overrideReason().isBlank()))throw new ResponseStatusException(HttpStatus.CONFLICT,"A warning override reason is required."); Assignment a=repo.save(new Assignment(s.getOrganization(),s,assignee,req.assignmentType(),req.title(),req.notes(),p.userId(),req.overrideReason())); audit.record(s.getOrganization(),p.userId(),"ASSIGNMENT_CREATED","Assignment",a.getId(),"SUCCESS",Map.of("scheduleId",s.getId().toString())); return view(p,a);}
 @Transactional public AssignmentView reassign(UserPrincipal p,UUID id,ReassignRequest req){Assignment a=assignment(p,id);AppUser replacement=user(p,req.assigneeId());List<ConflictView> found=conflicts.detect(p.organizationId(),a.getSchedule(),replacement);if(conflicts.hasBlocking(found))throw new ResponseStatusException(HttpStatus.CONFLICT,found.getFirst().message());if(!found.isEmpty()&&(req.overrideReason()==null||req.overrideReason().isBlank()))throw new ResponseStatusException(HttpStatus.CONFLICT,"A warning override reason is required.");try{a.reassign(replacement,req.overrideReason());}catch(IllegalStateException ex){throw new ResponseStatusException(HttpStatus.CONFLICT,ex.getMessage());}audit.record(a.getSchedule().getOrganization(),p.userId(),"ASSIGNMENT_REASSIGNED","Assignment",id,"SUCCESS",Map.of("assigneeId",replacement.getId().toString()));return view(p,a);}
 @Transactional public List<AssignmentView> scheduleDraftAssignments(UserPrincipal p,UUID scheduleId){ScheduleEvent s=schedule(p,scheduleId);List<Assignment> items=repo.findAllByOrganizationIdAndScheduleIdOrderByAssignmentTypeAsc(p.organizationId(),scheduleId);List<String> blockers=new ArrayList<>();for(Assignment a:items){List<ConflictView> found=conflicts.detect(p.organizationId(),s,a.getAssignee());if(conflicts.hasBlocking(found))blockers.add(a.getTitle()+": "+found.stream().filter(ConflictView::blocking).findFirst().orElseThrow().message());}if(!blockers.isEmpty())throw new ResponseStatusException(HttpStatus.CONFLICT,String.join("; ",blockers));items.stream().filter(a->a.getStatus()==AssignmentStatus.DRAFT).forEach(Assignment::schedule);return items.stream().map(a->view(p,a)).toList();}
 @Transactional(readOnly=true) public ReadinessView readiness(UserPrincipal p,UUID scheduleId){ScheduleEvent s=schedule(p,scheduleId);List<Assignment> items=repo.findAllByOrganizationIdAndScheduleIdOrderByAssignmentTypeAsc(p.organizationId(),scheduleId);List<String> blockers=new ArrayList<>();long unfilled=0;for(Assignment a:items){if(a.getAssignee()==null){unfilled++;blockers.add(a.getTitle()+" is unfilled.");continue;}for(ConflictView c:conflicts.detect(p.organizationId(),s,a.getAssignee()))if(c.blocking())blockers.add(a.getTitle()+": "+c.message());}return new ReadinessView(blockers.isEmpty(),unfilled,blockers);}
 private AssignmentView view(UserPrincipal p,Assignment a){AppUser u=a.getAssignee();return new AssignmentView(a.getId(),a.getSchedule().getId(),u==null?null:u.getId(),u==null?null:u.getFirstName()+" "+u.getLastName(),a.getAssignmentType(),a.getTitle(),a.getNotes(),a.getStatus(),a.getOverrideReason(),conflicts.detect(p.organizationId(),a.getSchedule(),u),a.getVersion());}
 private ScheduleEvent schedule(UserPrincipal p,UUID id){return schedules.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Schedule not found."));} private AppUser user(UserPrincipal p,UUID id){return users.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"User not found."));} private Assignment assignment(UserPrincipal p,UUID id){return repo.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Assignment not found."));}
}
