package com.mps.announcement.model;
import com.mps.organization.model.Organization; import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="announcement") public class Announcement{
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="organization_id") private Organization organization;
 @Column(nullable=false,length=200) private String title; @Column(nullable=false,columnDefinition="text") private String content;
 @Enumerated(EnumType.STRING) @Column(name="audience_type",nullable=false,length=24) private AudienceType audienceType; @Column(name="audience_reference_id") private UUID audienceReferenceId;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private AnnouncementStatus status=AnnouncementStatus.DRAFT;
 @Column(name="publish_at") private Instant publishAt; @Column(name="expires_at") private Instant expiresAt; @Column(name="published_at") private Instant publishedAt; @Column(name="created_by",nullable=false) private UUID createdBy; @Column(name="created_at",nullable=false) private Instant createdAt=Instant.now(); @Column(name="updated_at",nullable=false) private Instant updatedAt=Instant.now(); @Version private long version;
 protected Announcement(){} public Announcement(Organization org,String title,String content,AudienceType audience,UUID ref,Instant publishAt,Instant expiresAt,UUID creator){organization=org;this.title=title.trim();this.content=content.trim();audienceType=audience;audienceReferenceId=ref;this.publishAt=publishAt;this.expiresAt=expiresAt;createdBy=creator;status=publishAt!=null&&publishAt.isAfter(Instant.now())?AnnouncementStatus.SCHEDULED:AnnouncementStatus.DRAFT;}
 public void publish(){if(status!=AnnouncementStatus.DRAFT&&status!=AnnouncementStatus.SCHEDULED)throw new IllegalStateException("Only draft or scheduled announcements can be published.");status=AnnouncementStatus.PUBLISHED;publishedAt=Instant.now();updatedAt=publishedAt;}
 public void expire(){if(status==AnnouncementStatus.PUBLISHED){status=AnnouncementStatus.EXPIRED;updatedAt=Instant.now();}} public void archive(){status=AnnouncementStatus.ARCHIVED;updatedAt=Instant.now();}
 public UUID getId(){return id;} public Organization getOrganization(){return organization;} public String getTitle(){return title;} public String getContent(){return content;} public AudienceType getAudienceType(){return audienceType;} public UUID getAudienceReferenceId(){return audienceReferenceId;} public AnnouncementStatus getStatus(){return status;} public Instant getPublishAt(){return publishAt;} public Instant getExpiresAt(){return expiresAt;} public Instant getPublishedAt(){return publishedAt;} public Instant getCreatedAt(){return createdAt;}
}
