package com.mps.attendance.model;
import com.mps.auth.model.AppUser; import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="attendance_entry") public class AttendanceEntry {
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="register_id") private AttendanceRegister register; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="member_id") private AppUser member; @Enumerated(EnumType.STRING) @Column(name="attendance_status",nullable=false,length=24) private AttendanceStatus attendanceStatus; @Column(length=500) private String remarks; @Column(name="corrected_at") private Instant correctedAt; @Column(name="corrected_by") private UUID correctedBy; @Column(name="correction_reason",length=500) private String correctionReason; @Column(name="created_at",nullable=false) private Instant createdAt=Instant.now(); @Column(name="updated_at",nullable=false) private Instant updatedAt=Instant.now();
 protected AttendanceEntry(){} public AttendanceEntry(AttendanceRegister r,AppUser m,AttendanceStatus s,String remarks){register=r;member=m;attendanceStatus=s;this.remarks=norm(remarks);}
 public void update(AttendanceStatus s,String remarks){if(register.getStatus()==AttendanceRegisterStatus.FINALIZED)throw new IllegalStateException("Finalized attendance requires a correction workflow.");attendanceStatus=s;this.remarks=norm(remarks);updatedAt=Instant.now();}
 public void correct(AttendanceStatus s,String remarks,String reason,UUID by){if(register.getStatus()!=AttendanceRegisterStatus.FINALIZED)throw new IllegalStateException("Use the normal update workflow before finalization.");if(reason==null||reason.isBlank())throw new IllegalArgumentException("A correction reason is required.");attendanceStatus=s;this.remarks=norm(remarks);correctionReason=reason.trim();correctedBy=by;correctedAt=Instant.now();updatedAt=correctedAt;}
 public UUID getId(){return id;} public AttendanceRegister getRegister(){return register;} public AppUser getMember(){return member;} public AttendanceStatus getAttendanceStatus(){return attendanceStatus;} public String getRemarks(){return remarks;} public Instant getCorrectedAt(){return correctedAt;} public String getCorrectionReason(){return correctionReason;}
 private static String norm(String s){return s==null||s.isBlank()?null:s.trim();}
}
