package com.mps.operations.service;
import com.mps.audit.service.AuditService; import com.mps.auth.security.UserPrincipal; import com.mps.operations.dto.OperationsDtos.*; import com.mps.operations.model.*; import com.mps.operations.repository.*; import com.mps.organization.repository.OrganizationRepository; import org.springframework.beans.factory.annotation.Value; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.nio.file.*; import java.time.Instant; import java.util.*;
@Service public class OperationsService {private final BackupJobRepository backups;private final OperationalAlertRepository alerts;private final OrganizationRepository orgs;private final AuditService audit;private final JdbcTemplate jdbc;private final Path documentPath;private final Path backupPath;
 public OperationsService(BackupJobRepository b,OperationalAlertRepository a,OrganizationRepository o,AuditService au,JdbcTemplate j,@Value("${mps.storage.documents-path}")String docs,@Value("${mps.operations.backups-path:./data/backups}")String bp){backups=b;alerts=a;orgs=o;audit=au;jdbc=j;documentPath=Path.of(docs);backupPath=Path.of(bp);}
 @Transactional public BackupView requestBackup(UserPrincipal p,String type){if(!Set.of("FULL","DATABASE","DOCUMENTS","CONFIGURATION").contains(type))throw new IllegalArgumentException("Unsupported backup type.");var org=orgs.findById(p.organizationId()).orElseThrow();var job=new BackupJob(org,type,p.userId());var location=backupPath.resolve(p.organizationId().toString()).resolve(job.getId()+".request.json");try{Files.createDirectories(location.getParent());Files.writeString(location,"{\"backupJobId\":\""+job.getId()+"\",\"type\":\""+type+"\",\"requestedAt\":\""+Instant.now()+"\"}",StandardOpenOption.CREATE_NEW);}catch(Exception e){throw new IllegalStateException("Backup request could not be queued.",e);}job.markQueued(location.toString());backups.save(job);audit.record(org,p.userId(),"BACKUP_REQUESTED","BackupJob",job.getId(),"SUCCESS",Map.of("type",type));return view(job);}
 @Transactional(readOnly=true) public List<BackupView> backups(UserPrincipal p){return backups.findTop50ByOrganizationIdOrderByRequestedAtDesc(p.organizationId()).stream().map(this::view).toList();}
 @Transactional(readOnly=true) public List<AlertView> alerts(){return alerts.findTop100ByOrderByDetectedAtDesc().stream().map(this::view).toList();}
 @Transactional public AlertView acknowledge(UserPrincipal p,UUID id){var a=alerts.findByIdAndOrganizationId(id,p.organizationId()).orElseThrow();a.acknowledge(p.userId());return view(a);}
 public HealthView health(){boolean db=false,storage=false;Map<String,String> c=new LinkedHashMap<>();try{db=Boolean.TRUE.equals(jdbc.queryForObject("select true",Boolean.class));c.put("database",db?"UP":"DOWN");}catch(Exception e){c.put("database","DOWN");}try{Files.createDirectories(documentPath);storage=Files.isWritable(documentPath);c.put("documentStorage",storage?"UP":"DOWN");}catch(Exception e){c.put("documentStorage","DOWN");}long open=alerts.countByStatus("OPEN");return new HealthView(db&&storage?"UP":"DEGRADED",db,storage,open,Instant.now(),c);}
 private BackupView view(BackupJob b){return new BackupView(b.getId(),b.getBackupType(),b.getStatus(),b.getStorageLocation(),b.getChecksum(),b.getSizeBytes(),b.getMessage(),b.getRequestedAt(),b.getStartedAt(),b.getCompletedAt());}private AlertView view(OperationalAlert a){return new AlertView(a.getId(),a.getAlertType(),a.getSeverity(),a.getStatus(),a.getTitle(),a.getDetails(),a.getSource(),a.getDetectedAt(),a.getAcknowledgedAt(),a.getResolvedAt());}}
