package com.mps.document.service;
import org.springframework.beans.factory.annotation.Value; import org.springframework.core.io.*; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.nio.file.*; import java.security.*; import java.util.HexFormat; import java.util.UUID;
@Service public class DocumentStorageService { private final Path root; public record StoredFile(String originalFilename,String storedFilename,String contentType,long size,String sha256,String path){}
 public DocumentStorageService(@Value("${mps.storage.documents-path:./data/documents}") String path){root=Paths.get(path).toAbsolutePath().normalize();try{Files.createDirectories(root);}catch(IOException e){throw new IllegalStateException("Unable to initialize document storage.",e);}}
 public StoredFile store(UUID organizationId,UUID documentId,int version,MultipartFile file){validate(file);String original=Paths.get(file.getOriginalFilename()==null?"document":file.getOriginalFilename()).getFileName().toString();String ext=original.contains(".")?original.substring(original.lastIndexOf('.')).toLowerCase():"";String stored=UUID.randomUUID()+ext;Path dir=root.resolve(organizationId.toString()).resolve(documentId.toString()).resolve("v"+version).normalize();if(!dir.startsWith(root))throw new IllegalArgumentException("Invalid storage path.");try{Files.createDirectories(dir);Path target=dir.resolve(stored);MessageDigest digest=MessageDigest.getInstance("SHA-256");try(InputStream in=new DigestInputStream(file.getInputStream(),digest)){Files.copy(in,target,StandardCopyOption.REPLACE_EXISTING);}return new StoredFile(original,stored,contentType(file),file.getSize(),HexFormat.of().formatHex(digest.digest()),target.toString());}catch(IOException|NoSuchAlgorithmException e){throw new IllegalStateException("Unable to store document.",e);}}
 public Resource load(String storagePath){Path path=Paths.get(storagePath).toAbsolutePath().normalize();if(!path.startsWith(root))throw new IllegalArgumentException("Invalid storage path.");Resource resource=new FileSystemResource(path);if(!resource.exists()||!resource.isReadable())throw new IllegalStateException("Stored file is unavailable.");return resource;}
 private void validate(MultipartFile f){if(f==null||f.isEmpty())throw new IllegalArgumentException("A non-empty file is required.");if(f.getSize()>10*1024*1024)throw new IllegalArgumentException("File exceeds the 10 MB limit.");String type=contentType(f);if(!SetHolder.ALLOWED.contains(type))throw new IllegalArgumentException("Unsupported file type: "+type);}
 private String contentType(MultipartFile f){return f.getContentType()==null?"application/octet-stream":f.getContentType().toLowerCase();}
 private static final class SetHolder{private static final java.util.Set<String> ALLOWED=java.util.Set.of("application/pdf","text/plain","text/csv","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","image/png","image/jpeg");}
}
