package com.mps.document.service;
import com.mps.audit.service.AuditService; import com.mps.auth.model.AppUser; import com.mps.auth.repository.AppUserRepository; import com.mps.auth.security.UserPrincipal; import com.mps.document.dto.DocumentDtos.*; import com.mps.document.model.*; import com.mps.document.repository.*; import com.mps.organization.model.Organization; import com.mps.organization.repository.OrganizationRepository; import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@Service public class DocumentService { public record Download(Resource resource,String contentType,String filename){} private final DocumentRecordRepository documents; private final DocumentVersionRepository versions; private final OrganizationRepository organizations; private final AppUserRepository users; private final DocumentStorageService storage; private final AuditService audit;
 public DocumentService(DocumentRecordRepository d,DocumentVersionRepository v,OrganizationRepository o,AppUserRepository u,DocumentStorageService s,AuditService a){documents=d;versions=v;organizations=o;users=u;storage=s;audit=a;}
 @Transactional(readOnly=true) public List<DocumentView> list(UserPrincipal p){AppUser user=user(p);return documents.findAllByOrganizationIdAndStatusOrderByCreatedAtDesc(p.organizationId(),DocumentStatus.ACTIVE).stream().filter(d->canRead(user,d)).map(this::view).toList();}
 @Transactional public DocumentDetail upload(UserPrincipal p,String title,String category,DocumentAudienceType audience,UUID audienceRef,String notes,MultipartFile file){validateAudience(audience,audienceRef);Organization org=organizations.findById(p.organizationId()).orElseThrow();DocumentRecord d=documents.save(new DocumentRecord(org,title,category,audience,audienceRef,p.userId()));DocumentStorageService.StoredFile stored=storage.store(p.organizationId(),d.getId(),1,file);versions.save(new DocumentVersion(d,1,stored.originalFilename(),stored.storedFilename(),stored.contentType(),stored.size(),stored.sha256(),stored.path(),notes,p.userId()));audit.record(org,p.userId(),"DOCUMENT_UPLOADED","Document",d.getId(),"SUCCESS",Map.of("filename",stored.originalFilename()));return detail(p,d.getId());}
 @Transactional public DocumentDetail replace(UserPrincipal p,UUID id,String notes,MultipartFile file){DocumentRecord d=managed(p,id);int version;try{version=d.nextVersion();}catch(IllegalStateException ex){throw new ResponseStatusException(HttpStatus.CONFLICT,ex.getMessage());}DocumentStorageService.StoredFile stored=storage.store(p.organizationId(),d.getId(),version,file);versions.save(new DocumentVersion(d,version,stored.originalFilename(),stored.storedFilename(),stored.contentType(),stored.size(),stored.sha256(),stored.path(),notes,p.userId()));audit.record(d.getOrganization(),p.userId(),"DOCUMENT_VERSION_ADDED","Document",d.getId(),"SUCCESS",Map.of("version",version));return detail(p,id);}
 @Transactional(readOnly=true) public DocumentDetail detail(UserPrincipal p,UUID id){DocumentRecord d=readable(p,id);return new DocumentDetail(view(d),versions.findAllByDocumentIdOrderByVersionNumberDesc(id).stream().map(this::versionView).toList());}
 @Transactional(readOnly=true) public Download download(UserPrincipal p,UUID id,Integer number){DocumentRecord d=readable(p,id);int selected=number==null?d.getCurrentVersion():number;DocumentVersion v=versions.findByDocumentIdAndVersionNumber(id,selected).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Document version not found."));return new Download(storage.load(v.getStoragePath()),v.getContentType(),v.getOriginalFilename());}
 @Transactional public void archive(UserPrincipal p,UUID id){DocumentRecord d=managed(p,id);d.archive();audit.record(d.getOrganization(),p.userId(),"DOCUMENT_ARCHIVED","Document",id,"SUCCESS",Map.of());}
 private DocumentRecord managed(UserPrincipal p,UUID id){DocumentRecord d=documents.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Document not found."));if(!d.getOrganization().getId().equals(p.organizationId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Document is outside your organization.");return d;}
 private DocumentRecord readable(UserPrincipal p,UUID id){DocumentRecord d=managed(p,id);if(!canRead(user(p),d))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You do not have access to this document.");return d;}
 private AppUser user(UserPrincipal p){return users.findById(p.userId()).orElseThrow();}
 private boolean canRead(AppUser u,DocumentRecord d){if(u.getRoles().stream().anyMatch(r->r.getCode().equals("SUPER_ADMIN")||r.getCode().equals("ORG_ADMIN")))return true;return switch(d.getAudienceType()){case ORGANIZATION->true;case USER->Objects.equals(d.getAudienceReferenceId(),u.getId());case DEPARTMENT->u.getDepartment()!=null&&Objects.equals(d.getAudienceReferenceId(),u.getDepartment().getId());case GROUP->u.getGroup()!=null&&Objects.equals(d.getAudienceReferenceId(),u.getGroup().getId());case ROLE->u.getRoles().stream().anyMatch(r->Objects.equals(d.getAudienceReferenceId(),r.getId()));};}
 private void validateAudience(DocumentAudienceType type,UUID ref){if(type!=DocumentAudienceType.ORGANIZATION&&ref==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Audience reference is required.");}
 private DocumentView view(DocumentRecord d){return new DocumentView(d.getId(),d.getTitle(),d.getCategory(),d.getAudienceType(),d.getAudienceReferenceId(),d.getStatus(),d.getCurrentVersion(),d.getCreatedAt());}
 private VersionView versionView(DocumentVersion v){return new VersionView(v.getId(),v.getVersionNumber(),v.getOriginalFilename(),v.getContentType(),v.getSizeBytes(),v.getSha256(),v.getVersionNotes(),v.getUploadedAt());}
}
