package com.mps.document.model;
import com.mps.organization.model.Organization; import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="document_record") public class DocumentRecord {
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="organization_id") private Organization organization; @Column(nullable=false,length=200) private String title; @Column(length=100) private String category; @Enumerated(EnumType.STRING) @Column(name="audience_type",nullable=false,length=24) private DocumentAudienceType audienceType; @Column(name="audience_reference_id") private UUID audienceReferenceId; @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private DocumentStatus status=DocumentStatus.ACTIVE; @Column(name="current_version",nullable=false) private int currentVersion=1; @Column(name="uploaded_by",nullable=false) private UUID uploadedBy; @Column(name="created_at",nullable=false) private Instant createdAt=Instant.now(); @Column(name="updated_at",nullable=false) private Instant updatedAt=Instant.now(); @Column(name="archived_at") private Instant archivedAt; @Version private long version;
 protected DocumentRecord(){} public DocumentRecord(Organization o,String title,String category,DocumentAudienceType audience,UUID ref,UUID by){organization=o;this.title=title.trim();this.category=norm(category);audienceType=audience;audienceReferenceId=ref;uploadedBy=by;}
 public int nextVersion(){if(status==DocumentStatus.ARCHIVED)throw new IllegalStateException("Archived documents cannot receive new versions.");currentVersion++;updatedAt=Instant.now();return currentVersion;} public void archive(){status=DocumentStatus.ARCHIVED;archivedAt=Instant.now();updatedAt=archivedAt;}
 public UUID getId(){return id;} public Organization getOrganization(){return organization;} public String getTitle(){return title;} public String getCategory(){return category;} public DocumentAudienceType getAudienceType(){return audienceType;} public UUID getAudienceReferenceId(){return audienceReferenceId;} public DocumentStatus getStatus(){return status;} public int getCurrentVersion(){return currentVersion;} public Instant getCreatedAt(){return createdAt;}
 private static String norm(String s){return s==null||s.isBlank()?null:s.trim();}
}
