package com.mps.assignment;
import com.mps.assignment.dto.AssignmentDtos.*; import com.mps.assignment.service.AssignmentService; import com.mps.auth.security.UserPrincipal; import com.mps.common.ApiResponse; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/assignments") public class AssignmentController { private final AssignmentService service; public AssignmentController(AssignmentService s){service=s;}
 @GetMapping @PreAuthorize("hasAuthority('assignments.read')") public ApiResponse<List<AssignmentView>> list(@AuthenticationPrincipal UserPrincipal p,@RequestParam UUID scheduleId){return ApiResponse.ok("Assignments loaded.",service.list(p,scheduleId));}
 @PostMapping @PreAuthorize("hasAuthority('assignments.manage')") public ApiResponse<AssignmentView> create(@AuthenticationPrincipal UserPrincipal p,@Valid @RequestBody CreateAssignmentRequest r){return ApiResponse.ok("Assignment created.",service.create(p,r));}
 @PostMapping("/{id}/reassign") @PreAuthorize("hasAuthority('assignments.manage')") public ApiResponse<AssignmentView> reassign(@AuthenticationPrincipal UserPrincipal p,@PathVariable UUID id,@Valid @RequestBody ReassignRequest r){return ApiResponse.ok("Assignment reassigned.",service.reassign(p,id,r));}
 @PostMapping("/schedule/{scheduleId}") @PreAuthorize("hasAuthority('assignments.manage')") public ApiResponse<List<AssignmentView>> schedule(@AuthenticationPrincipal UserPrincipal p,@PathVariable UUID scheduleId){return ApiResponse.ok("Assignments scheduled.",service.scheduleDraftAssignments(p,scheduleId));}
 @GetMapping("/readiness/{scheduleId}") @PreAuthorize("hasAuthority('assignments.read')") public ApiResponse<ReadinessView> readiness(@AuthenticationPrincipal UserPrincipal p,@PathVariable UUID scheduleId){return ApiResponse.ok("Publication readiness evaluated.",service.readiness(p,scheduleId));}
}
