package com.mps.attendance.service;
import com.mps.attendance.dto.AttendanceDtos.*; import com.mps.attendance.model.*; import com.mps.attendance.repository.*; import com.mps.audit.service.AuditService; import com.mps.auth.model.*; import com.mps.auth.repository.AppUserRepository; import com.mps.auth.security.UserPrincipal; import com.mps.schedule.model.*; import com.mps.schedule.repository.ScheduleEventRepository; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@Service public class AttendanceService { private final AttendanceRegisterRepository registers; private final AttendanceEntryRepository entries; private final ScheduleEventRepository schedules; private final AppUserRepository users; private final AuditService audit;
 public AttendanceService(AttendanceRegisterRepository r,AttendanceEntryRepository e,ScheduleEventRepository s,AppUserRepository u,AuditService a){registers=r;entries=e;schedules=s;users=u;audit=a;}
 @Transactional public RegisterView getOrCreate(UserPrincipal p,UUID scheduleId){ScheduleEvent s=schedule(p,scheduleId);AttendanceRegister r=registers.findByOrganizationIdAndScheduleId(p.organizationId(),scheduleId).orElseGet(()->registers.save(new AttendanceRegister(s.getOrganization(),s,p.userId())));return view(r);}
 @Transactional public RegisterView save(UserPrincipal p,UUID scheduleId,SaveRegisterRequest req){AttendanceRegister r=register(p,scheduleId);if(r.getStatus()==AttendanceRegisterStatus.FINALIZED)throw new ResponseStatusException(HttpStatus.CONFLICT,"Attendance register is finalized.");Set<UUID> seen=new HashSet<>();for(EntryRequest x:req.entries()){if(!seen.add(x.memberId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Duplicate member in attendance request.");AppUser member=user(p,x.memberId());AttendanceEntry entry=entries.findByRegisterIdAndMemberId(r.getId(),member.getId()).orElseGet(()->new AttendanceEntry(r,member,x.status(),x.remarks()));if(entry.getId()!=null)entry.update(x.status(),x.remarks());entries.save(entry);}audit.record(r.getOrganization(),p.userId(),"ATTENDANCE_SAVED","AttendanceRegister",r.getId(),"SUCCESS",Map.of("scheduleId",scheduleId.toString(),"entries",req.entries().size()));return view(r);}
 @Transactional public RegisterView finalizeRegister(UserPrincipal p,UUID scheduleId){AttendanceRegister r=register(p,scheduleId);if(entries.findAllByRegisterIdOrderByMemberLastNameAscMemberFirstNameAsc(r.getId()).isEmpty())throw new ResponseStatusException(HttpStatus.CONFLICT,"At least one attendance entry is required.");try{r.finalizeRegister(p.userId());}catch(IllegalStateException ex){throw new ResponseStatusException(HttpStatus.CONFLICT,ex.getMessage());}audit.record(r.getOrganization(),p.userId(),"ATTENDANCE_FINALIZED","AttendanceRegister",r.getId(),"SUCCESS",Map.of("scheduleId",scheduleId.toString()));return view(r);}
 @Transactional public RegisterView correct(UserPrincipal p,UUID scheduleId,UUID memberId,CorrectionRequest req){AttendanceRegister r=register(p,scheduleId);AttendanceEntry e=entries.findByRegisterIdAndMemberId(r.getId(),memberId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Attendance entry not found."));try{e.correct(req.status(),req.remarks(),req.reason(),p.userId());}catch(IllegalStateException|IllegalArgumentException ex){throw new ResponseStatusException(HttpStatus.CONFLICT,ex.getMessage());}audit.record(r.getOrganization(),p.userId(),"ATTENDANCE_CORRECTED","AttendanceEntry",e.getId(),"SUCCESS",Map.of("reason",req.reason()));return view(r);}
 private AttendanceRegister register(UserPrincipal p,UUID scheduleId){ScheduleEvent s=schedule(p,scheduleId);return registers.findByOrganizationIdAndScheduleId(p.organizationId(),scheduleId).orElseGet(()->registers.save(new AttendanceRegister(s.getOrganization(),s,p.userId())));}
 private ScheduleEvent schedule(UserPrincipal p,UUID id){ScheduleEvent s=schedules.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Schedule not found."));if(!s.getOrganization().getId().equals(p.organizationId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Schedule is outside your organization.");if(s.getStatus()==ScheduleStatus.CANCELLED||s.getStatus()==ScheduleStatus.ARCHIVED)throw new ResponseStatusException(HttpStatus.CONFLICT,"Attendance cannot be recorded for this schedule.");return s;}
 private AppUser user(UserPrincipal p,UUID id){AppUser u=users.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Member not found."));if(!u.getOrganization().getId().equals(p.organizationId())||u.getStatus()!=UserStatus.ACTIVE)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Member is not active in this organization.");return u;}
 private RegisterView view(AttendanceRegister r){List<EntryView> list=entries.findAllByRegisterIdOrderByMemberLastNameAscMemberFirstNameAsc(r.getId()).stream().map(e->new EntryView(e.getId(),e.getMember().getId(),e.getMember().getFirstName()+" "+e.getMember().getLastName(),e.getAttendanceStatus(),e.getRemarks(),e.getCorrectedAt(),e.getCorrectionReason())).toList();return new RegisterView(r.getId(),r.getSchedule().getId(),r.getSchedule().getTitle(),r.getStatus(),r.getFinalizedAt(),list);}
}
