package com.mps.settings.service;
import com.mps.audit.service.AuditService; import com.mps.auth.security.UserPrincipal; import com.mps.organization.repository.OrganizationRepository; import com.mps.settings.dto.SettingsDtos.*; import com.mps.settings.model.SystemSetting; import com.mps.settings.repository.SystemSettingRepository;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class SystemSettingsService {private final SystemSettingRepository repo;private final OrganizationRepository orgs;private final AuditService audit;
 public SystemSettingsService(SystemSettingRepository r,OrganizationRepository o,AuditService a){repo=r;orgs=o;audit=a;}
 @Transactional(readOnly=true) public List<SettingView> list(UserPrincipal p){return repo.findByOrganizationIdOrderByKey(p.organizationId()).stream().map(this::view).toList();}
 @Transactional public SettingView put(UserPrincipal p,UpdateSettingRequest r){validate(r);var org=orgs.findById(p.organizationId()).orElseThrow();var s=repo.findByOrganizationIdAndKey(p.organizationId(),r.key().trim()).orElseGet(()->new SystemSetting(org,r.key().trim(),r.value(),r.valueType(),r.description(),p.userId()));s.update(r.value(),r.valueType(),r.description(),p.userId());repo.save(s);audit.record(org,p.userId(),"SETTING_UPDATED","SystemSetting",s.getId(),"SUCCESS",Map.of("key",s.getKey()));return view(s);}
 private void validate(UpdateSettingRequest r){try{switch(r.valueType()){case "BOOLEAN"-> {if(!r.value().equalsIgnoreCase("true")&&!r.value().equalsIgnoreCase("false"))throw new IllegalArgumentException();}case "INTEGER"->Long.parseLong(r.value());case "DECIMAL"->new java.math.BigDecimal(r.value());case "DURATION"->java.time.Duration.parse(r.value());default->{}}}catch(Exception e){throw new IllegalArgumentException("Setting value does not match its declared type.");}}
 private SettingView view(SystemSetting s){return new SettingView(s.getId(),s.getKey(),s.getValue(),s.getValueType(),s.getDescription(),s.getUpdatedAt(),s.getUpdatedBy());}}
