import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom/client';
import './styles.css';

type User={id:string;organizationId:string;email:string;firstName:string;lastName:string;roles:string[]};
type AuthPayload={accessToken:string;refreshToken:string;expiresInSeconds:number;user:User};
type ApiResponse<T>={success:boolean;message:string;data:T};
type Schedule={id:string;seriesId?:string;occurrenceNumber:number;title:string;location?:string;startAt:string;endAt:string;status:'DRAFT'|'PUBLISHED'|'COMPLETED'|'CANCELLED'|'ARCHIVED';recurrenceFrequency:'NONE'|'DAILY'|'WEEKLY'|'MONTHLY'};
type Notification={id:string;type:string;title:string;message:string;relatedEntityType?:string;relatedEntityId?:string;read:boolean;createdAt:string};
type Announcement={id:string;title:string;content:string;audienceType:string;status:'DRAFT'|'SCHEDULED'|'PUBLISHED'|'EXPIRED'|'ARCHIVED';publishAt?:string;expiresAt?:string;createdAt:string};
type DocumentItem={id:string;title:string;category?:string;status:string;currentVersion:number;createdAt:string};
type AttendanceRegister={id:string;scheduleId:string;scheduleTitle:string;status:'DRAFT'|'FINALIZED';finalizedAt?:string;entries:{id:string;memberId:string;memberName:string;status:string;remarks?:string}[]};
type DashboardSummary={activeUsers:number;upcomingSchedules:number;draftSchedules:number;publishedSchedules:number;openAssignments:number;completedAssignments:number;unreadNotifications:number;activeDocuments:number;attendanceRate:number;generatedAt:string};
type ReportRow={category:string;label:string;count:number;status:string}; type OperationalReport={reportType:string;from:string;to:string;generatedAt:string;rows:ReportRow[]};
type AuditEvent={id:string;actorUserId?:string;action:string;entityType:string;entityId?:string;outcome:string;details:string;occurredAt:string};
type Section='dashboard'|'schedules'|'announcements'|'notifications'|'attendance'|'documents'|'reports'|'audit'; type ViewMode='week'|'month';
const API=import.meta.env.VITE_API_URL??'http://localhost:8080/api/v1';
const defaultStart=new Date(Date.now()+86400000); defaultStart.setHours(18,0,0,0);
function isoLocal(d:Date){const o=d.getTimezoneOffset()*60000;return new Date(d.getTime()-o).toISOString().slice(0,16)}

function App(){
 const [accessToken,setAccessToken]=useState(()=>sessionStorage.getItem('mps.access')??''); const [refreshToken,setRefreshToken]=useState(()=>localStorage.getItem('mps.refresh')??'');
 const [user,setUser]=useState<User|null>(null); const [email,setEmail]=useState('admin@mps.local'); const [password,setPassword]=useState('ChangeThisPassword123!'); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const [section,setSection]=useState<Section>('dashboard'); const [viewMode,setViewMode]=useState<ViewMode>('week'); const [anchor,setAnchor]=useState(new Date()); const [schedules,setSchedules]=useState<Schedule[]>([]); const [notifications,setNotifications]=useState<Notification[]>([]); const [announcements,setAnnouncements]=useState<Announcement[]>([]); const [unread,setUnread]=useState(0);
 const [showScheduleForm,setShowScheduleForm]=useState(false); const [title,setTitle]=useState('Weekly coordination meeting'); const [location,setLocation]=useState('Main Hall'); const [startAt,setStartAt]=useState(isoLocal(defaultStart)); const [endAt,setEndAt]=useState(isoLocal(new Date(defaultStart.getTime()+7200000))); const [frequency,setFrequency]=useState<'NONE'|'DAILY'|'WEEKLY'|'MONTHLY'>('NONE'); const [count,setCount]=useState(1);
 const [announcementTitle,setAnnouncementTitle]=useState('Important update'); const [announcementContent,setAnnouncementContent]=useState('Please review the latest organization update.');
 const [documents,setDocuments]=useState<DocumentItem[]>([]); const [dashboard,setDashboard]=useState<DashboardSummary|null>(null); const [report,setReport]=useState<OperationalReport|null>(null); const [reportType,setReportType]=useState('overview'); const [auditEvents,setAuditEvents]=useState<AuditEvent[]>([]); const [auditAction,setAuditAction]=useState(''); const [documentTitle,setDocumentTitle]=useState('Organization guide'); const [documentFile,setDocumentFile]=useState<File|null>(null); const [attendance,setAttendance]=useState<AttendanceRegister|null>(null);
 const range=useMemo(()=>{const from=new Date(anchor),to=new Date(anchor);if(viewMode==='week'){const day=(from.getDay()+6)%7;from.setDate(from.getDate()-day);from.setHours(0,0,0,0);to.setTime(from.getTime());to.setDate(to.getDate()+7)}else{from.setDate(1);from.setHours(0,0,0,0);to.setTime(from.getTime());to.setMonth(to.getMonth()+1)}return{from,to}},[anchor,viewMode]);
 const canManageAnnouncements=user?.roles.some(r=>r==='ORG_ADMIN'||r==='COORDINATOR'||r==='SUPER_ADMIN');
 useEffect(()=>{if(!accessToken)return;fetch(`${API}/auth/me`,{headers:{Authorization:`Bearer ${accessToken}`}}).then(async r=>{if(!r.ok)throw new Error();return(await r.json())as ApiResponse<User>}).then(x=>setUser(x.data)).catch(()=>void signOut(false))},[accessToken]);
 useEffect(()=>{if(!user)return;void loadNotificationSummary();void loadDashboard();},[user]);
 useEffect(()=>{if(section==='schedules'&&accessToken)void loadSchedules();if(section==='notifications'&&accessToken)void loadNotifications();if(section==='announcements'&&accessToken)void loadAnnouncements();if(section==='documents'&&accessToken)void loadDocuments();if(section==='attendance'&&accessToken)void loadSchedules();if(section==='reports'&&accessToken)void loadReport();if(section==='audit'&&accessToken)void loadAudit()},[section,accessToken,range.from.getTime(),range.to.getTime()]);
 async function api<T>(path:string,init:RequestInit={}){const response=await fetch(`${API}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`,...(init.headers??{})}});const result=await response.json()as ApiResponse<T>;if(!response.ok||!result.success)throw new Error(result.message||'Request failed.');return result.data}
 async function signIn(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const x=await r.json()as ApiResponse<AuthPayload>;if(!r.ok||!x.success)throw new Error(x.message);sessionStorage.setItem('mps.access',x.data.accessToken);localStorage.setItem('mps.refresh',x.data.refreshToken);setAccessToken(x.data.accessToken);setRefreshToken(x.data.refreshToken);setUser(x.data.user)}catch(e){setMessage(e instanceof Error?e.message:'Login failed.')}finally{setBusy(false)}}
 async function signOut(callApi=true){if(callApi&&refreshToken)await fetch(`${API}/auth/logout`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})}).catch(()=>undefined);sessionStorage.removeItem('mps.access');localStorage.removeItem('mps.refresh');setAccessToken('');setRefreshToken('');setUser(null)}
 async function loadSchedules(){try{setSchedules(await api<Schedule[]>(`/schedules?from=${encodeURIComponent(range.from.toISOString())}&to=${encodeURIComponent(range.to.toISOString())}`))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load schedules.')}}
 async function loadNotifications(){try{setNotifications(await api<Notification[]>('/notifications'));await loadNotificationSummary()}catch(e){setMessage(e instanceof Error?e.message:'Unable to load notifications.')}}
 async function loadNotificationSummary(){try{const x=await api<{unreadCount:number}>('/notifications/summary');setUnread(x.unreadCount)}catch{setUnread(0)}}
 async function loadAnnouncements(){try{setAnnouncements(await api<Announcement[]>('/announcements'))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load announcements.')}}
 async function loadDocuments(){try{setDocuments(await api<DocumentItem[]>('/documents'))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load documents.')}}
 async function loadDashboard(){try{setDashboard(await api<DashboardSummary>('/reports/dashboard'))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load dashboard.')}}
 async function loadReport(){try{setReport(await api<OperationalReport>(`/reports?type=${encodeURIComponent(reportType)}`))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load report.')}}
 async function loadAudit(){try{setAuditEvents(await api<AuditEvent[]>(`/audit?action=${encodeURIComponent(auditAction)}`))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load audit events.')}}
 async function downloadExport(format:string){const r=await fetch(`${API}/reports/export?type=${encodeURIComponent(reportType)}&format=${format}`,{headers:{Authorization:`Bearer ${accessToken}`}});if(!r.ok){setMessage('Unable to export report.');return}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mps-${reportType}-report.${format}`;a.click();URL.revokeObjectURL(url)}
 async function downloadAudit(){const r=await fetch(`${API}/audit/export?action=${encodeURIComponent(auditAction)}`,{headers:{Authorization:`Bearer ${accessToken}`}});if(!r.ok){setMessage('Unable to export audit log.');return}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='mps-audit-export.csv';a.click();URL.revokeObjectURL(url)}
 async function loadAttendance(scheduleId:string){try{setAttendance(await api<AttendanceRegister>(`/attendance/schedule/${scheduleId}`))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load attendance.')}}
 async function finalizeAttendance(){if(!attendance)return;try{setAttendance(await api<AttendanceRegister>(`/attendance/schedule/${attendance.scheduleId}/finalize`,{method:'POST'}));setMessage('Attendance register finalized.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to finalize attendance.')}}
 async function uploadDocument(e:FormEvent){e.preventDefault();if(!documentFile)return;setBusy(true);try{const body=new FormData();body.append('title',documentTitle);body.append('audienceType','ORGANIZATION');body.append('file',documentFile);const response=await fetch(`${API}/documents`,{method:'POST',headers:{Authorization:`Bearer ${accessToken}`},body});const result=await response.json()as ApiResponse<unknown>;if(!response.ok||!result.success)throw new Error(result.message);await loadDocuments();setDocumentFile(null);setMessage('Document uploaded.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to upload document.')}finally{setBusy(false)}}
 async function downloadDocument(id:string){const response=await fetch(`${API}/documents/${id}/download`,{headers:{Authorization:`Bearer ${accessToken}`}});if(!response.ok){setMessage('Unable to download document.');return}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='document';a.click();URL.revokeObjectURL(url)}
 async function createSchedule(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/schedules',{method:'POST',body:JSON.stringify({title,location,description:'',startAt:new Date(startAt).toISOString(),endAt:new Date(endAt).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',recurrence:{frequency,interval:1,count:frequency==='NONE'?1:count}})});setShowScheduleForm(false);await loadSchedules();setMessage('Schedule created as a draft.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to create schedule.')}finally{setBusy(false)}}
 async function publishSchedule(id:string){try{await api(`/schedules/${id}/publish`,{method:'POST'});await loadSchedules();await loadNotificationSummary()}catch(e){setMessage(e instanceof Error?e.message:'Unable to publish schedule.')}}
 async function createAnnouncement(e:FormEvent){e.preventDefault();setBusy(true);try{const a=await api<Announcement>('/announcements',{method:'POST',body:JSON.stringify({title:announcementTitle,content:announcementContent,audienceType:'ORGANIZATION'})});await api(`/announcements/${a.id}/publish`,{method:'POST'});await loadAnnouncements();await loadNotificationSummary();setMessage('Announcement published.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to publish announcement.')}finally{setBusy(false)}}
 async function markRead(id:string){try{await api(`/notifications/${id}/read`,{method:'PUT'});await loadNotifications()}catch(e){setMessage(e instanceof Error?e.message:'Unable to update notification.')}}
 function move(direction:number){const n=new Date(anchor);viewMode==='week'?n.setDate(n.getDate()+direction*7):n.setMonth(n.getMonth()+direction);setAnchor(n)}
 if(!user)return <main className="login-shell"><section className="brand-panel"><p className="eyebrow">MPS · Sprint 8</p><h1>Coordinate clearly.<br/>Communicate instantly.</h1><p>Schedules, attendance, documents, announcements, and notifications now work together in one secure organization workspace.</p></section><form className="login-card" onSubmit={signIn}><div><p className="eyebrow">Welcome back</p><h2>Sign in to MPS</h2></div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<p className="error">{message}</p>}<button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></main>;
 return <><a className="skip-link" href="#main-content">Skip to main content</a><main className="app-shell"><aside><div className="logo">MPS</div><nav aria-label="Primary navigation"><button className={section==='dashboard'?'active':''} onClick={()=>setSection('dashboard')}>Dashboard</button><button className={section==='schedules'?'active':''} onClick={()=>setSection('schedules')}>Schedules</button><button className={section==='announcements'?'active':''} onClick={()=>setSection('announcements')}>Announcements</button><button className={section==='notifications'?'active':''} onClick={()=>setSection('notifications')}>Notifications {unread>0&&<b className="badge">{unread}</b>}</button><button className={section==='attendance'?'active':''} onClick={()=>setSection('attendance')}>Attendance</button><button className={section==='documents'?'active':''} onClick={()=>setSection('documents')}>Documents</button><button className={section==='reports'?'active':''} onClick={()=>setSection('reports')}>Reports</button><button className={section==='audit'?'active':''} onClick={()=>setSection('audit')}>Audit</button></nav></aside><section id="main-content" className="workspace" tabIndex={-1}><header><div><p className="eyebrow">Organization workspace</p><h2>{section==='dashboard'?`Good morning, ${user.firstName}`:section[0].toUpperCase()+section.slice(1)}</h2></div><button className="secondary" onClick={()=>void signOut()}>Sign out</button></header>{message&&<p className="notice">{message}</p>}
 {section==='dashboard'&&<div className="grid"><article className="hero"><p className="eyebrow">Sprint 8 active</p><h3>Operational insight is now available.</h3><p>Dashboards, filtered reports, exports, and audit review are organization-scoped and permission controlled.</p></article><article><span>Active users</span><strong>{dashboard?.activeUsers??'—'}</strong></article><article><span>Upcoming schedules</span><strong>{dashboard?.upcomingSchedules??'—'}</strong></article><article><span>Attendance rate</span><strong>{dashboard?`${dashboard.attendanceRate}%`:'—'}</strong></article><article><span>Unread notifications</span><strong>{unread}</strong></article><article><span>Roles</span><strong>{user.roles.join(', ')}</strong></article><article><span>Account</span><strong>{user.email}</strong></article></div>}
 {section==='schedules'&&<div className="calendar-shell"><div className="calendar-toolbar"><div><button className="secondary" onClick={()=>move(-1)}>Previous</button><button className="secondary" onClick={()=>setAnchor(new Date())}>Today</button><button className="secondary" onClick={()=>move(1)}>Next</button></div><strong>{range.from.toLocaleDateString()} – {new Date(range.to.getTime()-1).toLocaleDateString()}</strong><div><button className={viewMode==='week'?'':'secondary'} onClick={()=>setViewMode('week')}>Week</button><button className={viewMode==='month'?'':'secondary'} onClick={()=>setViewMode('month')}>Month</button><button onClick={()=>setShowScheduleForm(!showScheduleForm)}>New schedule</button></div></div>{showScheduleForm&&<form className="schedule-form" onSubmit={createSchedule}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Starts<input type="datetime-local" value={startAt} onChange={e=>setStartAt(e.target.value)} required/></label><label>Ends<input type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)} required/></label><label>Repeats<select value={frequency} onChange={e=>setFrequency(e.target.value as typeof frequency)}><option value="NONE">Does not repeat</option><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option></select></label>{frequency!=='NONE'&&<label>Occurrences<input type="number" min="1" max="104" value={count} onChange={e=>setCount(Number(e.target.value))}/></label>}<button disabled={busy}>Save draft</button></form>}<div className="schedule-list">{schedules.length===0&&<article className="empty"><h3>No schedules in this range</h3></article>}{schedules.map(s=><article className="schedule-item" key={s.id}><div className="date-badge"><strong>{new Date(s.startAt).getDate()}</strong><span>{new Date(s.startAt).toLocaleString(undefined,{month:'short'})}</span></div><div><div className="schedule-title"><h3>{s.title}</h3><span className={`status ${s.status.toLowerCase()}`}>{s.status}</span></div><p>{new Date(s.startAt).toLocaleString()} · {s.location||'No location'}</p></div>{s.status==='DRAFT'&&<button onClick={()=>void publishSchedule(s.id)}>Publish</button>}</article>)}</div></div>}
 {section==='announcements'&&<div className="two-column">{canManageAnnouncements&&<form className="panel-form" onSubmit={createAnnouncement}><h3>Publish announcement</h3><label>Title<input value={announcementTitle} onChange={e=>setAnnouncementTitle(e.target.value)} required/></label><label>Message<textarea value={announcementContent} onChange={e=>setAnnouncementContent(e.target.value)} rows={7} required/></label><button disabled={busy}>Publish to organization</button></form>}<div className="stack"><h3>Announcements</h3>{announcements.map(a=><article key={a.id}><div className="schedule-title"><h3>{a.title}</h3><span className={`status ${a.status.toLowerCase()}`}>{a.status}</span></div><p>{a.content}</p><small>{new Date(a.createdAt).toLocaleString()}</small></article>)}</div></div>}

 {section==='attendance'&&<div className="two-column"><div className="stack"><h3>Select a schedule</h3>{schedules.map(s=><article key={s.id}><div className="schedule-title"><h3>{s.title}</h3><span className={`status ${s.status.toLowerCase()}`}>{s.status}</span></div><p>{new Date(s.startAt).toLocaleString()}</p><button className="secondary" onClick={()=>void loadAttendance(s.id)}>Open register</button></article>)}</div><div className="stack"><h3>Attendance register</h3>{!attendance&&<article className="empty"><p>Select a schedule to view or create its register.</p></article>}{attendance&&<article><div className="schedule-title"><h3>{attendance.scheduleTitle}</h3><span className={`status ${attendance.status.toLowerCase()}`}>{attendance.status}</span></div><p>{attendance.entries.length} attendance entries</p>{attendance.entries.map(e=><p key={e.id}><strong>{e.memberName}</strong> · {e.status}</p>)}{attendance.status==='DRAFT'&&<button onClick={()=>void finalizeAttendance()}>Finalize register</button>}</article>}</div></div>}
 {section==='documents'&&<div className="two-column"><form className="panel-form" onSubmit={uploadDocument}><h3>Upload document</h3><label>Title<input value={documentTitle} onChange={e=>setDocumentTitle(e.target.value)} required/></label><label>File<input type="file" accept=".pdf,.txt,.csv,.docx,.xlsx,.png,.jpg,.jpeg" onChange={e=>setDocumentFile(e.target.files?.[0]??null)} required/></label><button disabled={busy||!documentFile}>Upload for organization</button><small>Allowed files up to 10 MB.</small></form><div className="stack"><h3>Documents</h3>{documents.length===0&&<article className="empty"><p>No active documents.</p></article>}{documents.map(d=><article key={d.id}><div className="schedule-title"><h3>{d.title}</h3><span className="status published">v{d.currentVersion}</span></div><p>{d.category||'General'} · {new Date(d.createdAt).toLocaleDateString()}</p><button className="secondary" onClick={()=>void downloadDocument(d.id)}>Download</button></article>)}</div></div>}


 {section==='reports'&&<div className="stack"><div className="calendar-toolbar"><div><select value={reportType} onChange={e=>setReportType(e.target.value)}><option value="overview">Overview</option><option value="schedules">Schedules</option><option value="assignments">Assignments</option><option value="attendance">Attendance</option><option value="users">Users</option></select><button onClick={()=>void loadReport()}>Generate</button></div><div><button className="secondary" onClick={()=>void downloadExport('csv')}>CSV</button><button className="secondary" onClick={()=>void downloadExport('xlsx')}>Excel</button><button className="secondary" onClick={()=>void downloadExport('pdf')}>PDF</button></div></div>{report&&<article><div className="schedule-title"><h3>{report.reportType} report</h3><span className="status published">{new Date(report.generatedAt).toLocaleString()}</span></div><div className="report-table"><div className="report-row heading"><strong>Category</strong><strong>Label</strong><strong>Status</strong><strong>Count</strong></div>{report.rows.map((r,i)=><div className="report-row" key={`${r.category}-${r.label}-${i}`}><span>{r.category}</span><span>{r.label}</span><span>{r.status}</span><strong>{r.count}</strong></div>)}</div></article>}</div>}
 {section==='audit'&&<div className="stack"><div className="calendar-toolbar"><div><input placeholder="Filter by action" value={auditAction} onChange={e=>setAuditAction(e.target.value)}/><button onClick={()=>void loadAudit()}>Search</button></div><button className="secondary" onClick={()=>void downloadAudit()}>Export CSV</button></div>{auditEvents.map(e=><article key={e.id}><div className="schedule-title"><h3>{e.action}</h3><span className={`status ${e.outcome.toLowerCase()}`}>{e.outcome}</span></div><p>{e.entityType}{e.entityId?` · ${e.entityId}`:''}</p><small>{new Date(e.occurredAt).toLocaleString()} · Actor {e.actorUserId??'System'}</small></article>)}</div>}

 {section==='notifications'&&<div className="stack">{notifications.length===0&&<article className="empty"><h3>No notifications yet</h3></article>}{notifications.map(n=><article className={`notification-item ${n.read?'':'unread'}`} key={n.id}><div><div className="schedule-title"><h3>{n.title}</h3>{!n.read&&<span className="status published">NEW</span>}</div><p>{n.message}</p><small>{new Date(n.createdAt).toLocaleString()}</small></div>{!n.read&&<button className="secondary" onClick={()=>void markRead(n.id)}>Mark read</button>}</article>)}</div>}
 </section></main><div id="live-region" className="sr-only" aria-live="polite">{message}</div></>
}
// Accessibility: skip navigation is rendered before the application shell.
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
